name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: CSNfribeloppAPI-0.0.1-SNAPSHOT.jar
          path: target/CSNfribeloppAPI-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Lägg till denna rad för att ge rätt behörighet till ID-token

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: CSNfribeloppAPI-0.0.1-SNAPSHOT.jar

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7A53051EBF34F70BDACE03CC158FF58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2DF0386EDE9847EAA7C904279AB6EE40 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CF79E5FDA4A643C9B9323BA759329FF3 }}
          auth-type: SERVICE_PRINCIPAL  # Använder SERVICE_PRINCIPAL för autentisering
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fribeloppsraknaren'  # Namnet på din Azure Web App
          package: ${{ github.workspace }}/CSNfribeloppAPI-0.0.1-SNAPSHOT.jar
